[package]
name = "topics"
version = "0.1.0"
authors = ["bryan huizi <bryan.huizi@magnet360.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.4"
crossbeam-channel = "0.4.2"
exitfailure = "0.5.1"